name: dottorrent-cli
on:
  workflow_dispatch:
    inputs:
      name:
        description: Name of the torrent file
        required: true
        default: Firefox Setup 95.0.1
      comment:
        description: Comment
        required: true
        default: Firefox Setup 95.0.1 win64 en-US by torrent-webseed-creator
      url:
        description: URL of the file
        required: true
        default: 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/95.0.1/win64/en-US/Firefox%20Setup%2095.0.1.exe'
      file_name:
        description: File name of the file in the torrent
        required: true
        default: Firefox Setup 95.0.1.exe
      maximize_disk_space:
        description: Maximize disk space. Set to true if getting out of disk space error
        default: false
        
jobs:
  create_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: github.event.inputs.maximize_disk_space == 'true'
        uses: easimon/maximize-build-space@v5
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          
      - name: Install dottorrent-cli
        run: pipx install dottorrent-cli
        
      - name: Download file
        run: aria2c -x 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.url }}"
        
      - name: Create torrent using dottorrent-cli
        run: dottorrent --web_seed "${{ github.event.inputs.url }}" --source "torrent-webseed-creator" --comment "${{ github.event.inputs.comment }}" "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.name }}.torrent"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.name }}.torrent