name: torf-cli
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the torrent file"
        required: true
        default: "Firefox Setup 90.0.2"
      comment:
        description: "Comment"
        required: true
        default: "Firefox Setup 90.0.2 win64 en-US by torrent-webseed-creator"
      url:
        description: "URL of the file"
        required: true
        default: "https://download-installer.cdn.mozilla.net/pub/firefox/releases/90.0.2/win64/en-US/Firefox%20Setup%2090.0.2.exe"
      file_name:
        description: "File name of the file in the torrent"
        required: true
        default: "Firefox Setup 90.0.2.exe"
      maximize_disk_space:
        description: "Maximize disk space. Set to true if getting out of disk space error"
        required: true
        default: "false"
        
jobs:
  create-torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        if: ${{ github.event.inputs.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install torf-cli
        run: sudo pip3 install torf-cli
        
      - name: Download file
        run: aria2c -x 16 -o "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.url }}"
        
      - name: Create torrent using torf-cli
        run: torf "${{ github.event.inputs.file_name }}" -o "${{ github.event.inputs.name }}.torrent" -w "${{ github.event.inputs.url }}" -c "${{ github.event.inputs.comment }}" -s "torrent-webseed-creator"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.name }}.torrent